; NOTE: Assertions have been autogenerated by utils/update_test_checks.py UTC_ARGS: --version 5
; RUN: opt < %s -passes='sroa<preserve-cfg>' -S | FileCheck %s
; RUN: opt < %s -passes='sroa<modify-cfg>' -S | FileCheck %s
target datalayout = "e-p:64:64:64-i1:8:8-i8:8:8-i16:16:16-i32:32:32-i64:32:64-f32:32:32-f64:64:64-v64:64:64-v128:128:128-a0:0:64-n8:16:32:64"

;
; Positive tests for the init + RMW tree-merge rewrite in SROA.
;
; The pattern this exercises:
;   - a single full-width init store at the top,
;   - one or more rounds of per-slice load-process-store,
;   - a single full-width load at the end.
;
; The rewrite should:
;   - replace each partial load with an extractvector from the current
;     per-slice value,
;   - thread each slice's SSA value through the rounds via the user's
;     compute (no selects/blends),
;   - tree-merge the final per-slice values into the final alloca value.
;

; Canonical single-round RMW: 2 slices, each loaded, processed, stored back.
define <4 x float> @single_round(<4 x float> %init, <2 x float> %a, <2 x float> %b) {
; CHECK-LABEL: define <4 x float> @single_round(
; CHECK-SAME: <4 x float> [[INIT:%.*]], <2 x float> [[A:%.*]], <2 x float> [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[INIT_EXTRACT_EXTRACT:%.*]] = shufflevector <4 x float> [[INIT]], <4 x float> poison, <2 x i32> <i32 0, i32 1>
; CHECK-NEXT:    [[INIT_EXTRACT_EXTRACT1:%.*]] = shufflevector <4 x float> [[INIT]], <4 x float> poison, <2 x i32> <i32 2, i32 3>
; CHECK-NEXT:    [[R0:%.*]] = fadd <2 x float> [[INIT_EXTRACT_EXTRACT]], [[A]]
; CHECK-NEXT:    [[R1:%.*]] = fadd <2 x float> [[INIT_EXTRACT_EXTRACT1]], [[B]]
; CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <2 x float> [[R0]], <2 x float> [[R1]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    ret <4 x float> [[TMP0]]
;
entry:
  %alloca = alloca [4 x float], align 16
  store <4 x float> %init, ptr %alloca, align 16

  %p0 = getelementptr inbounds [4 x float], ptr %alloca, i32 0, i32 0
  %v0 = load <2 x float>, ptr %p0, align 8
  %r0 = fadd <2 x float> %v0, %a
  store <2 x float> %r0, ptr %p0, align 8

  %p1 = getelementptr inbounds [4 x float], ptr %alloca, i32 0, i32 2
  %v1 = load <2 x float>, ptr %p1, align 8
  %r1 = fadd <2 x float> %v1, %b
  store <2 x float> %r1, ptr %p1, align 8

  %result = load <4 x float>, ptr %alloca, align 16
  ret <4 x float> %result
}

; Multi-round RMW: the same 2-slice partition is updated twice.
; Round 2's load at each slice should read round 1's stored value
; (the per-slice SSA chain), not the init value.
define <4 x float> @multi_round(<4 x float> %init,
; CHECK-LABEL: define <4 x float> @multi_round(
; CHECK-SAME: <4 x float> [[INIT:%.*]], <2 x float> [[A1:%.*]], <2 x float> [[B1:%.*]], <2 x float> [[A2:%.*]], <2 x float> [[B2:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[INIT_EXTRACT_EXTRACT:%.*]] = shufflevector <4 x float> [[INIT]], <4 x float> poison, <2 x i32> <i32 0, i32 1>
; CHECK-NEXT:    [[INIT_EXTRACT_EXTRACT1:%.*]] = shufflevector <4 x float> [[INIT]], <4 x float> poison, <2 x i32> <i32 2, i32 3>
; CHECK-NEXT:    [[R0_1:%.*]] = fadd <2 x float> [[INIT_EXTRACT_EXTRACT]], [[A1]]
; CHECK-NEXT:    [[R1_1:%.*]] = fadd <2 x float> [[INIT_EXTRACT_EXTRACT1]], [[B1]]
; CHECK-NEXT:    [[R0_2:%.*]] = fadd <2 x float> [[R0_1]], [[A2]]
; CHECK-NEXT:    [[R1_2:%.*]] = fadd <2 x float> [[R1_1]], [[B2]]
; CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <2 x float> [[R0_2]], <2 x float> [[R1_2]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    ret <4 x float> [[TMP0]]
;
  <2 x float> %a1, <2 x float> %b1,
  <2 x float> %a2, <2 x float> %b2) {
entry:
  %alloca = alloca [4 x float], align 16
  store <4 x float> %init, ptr %alloca, align 16

  %p0 = getelementptr inbounds [4 x float], ptr %alloca, i32 0, i32 0
  %p1 = getelementptr inbounds [4 x float], ptr %alloca, i32 0, i32 2

  ; round 1
  %v0.1 = load  <2 x float>, ptr %p0, align 8
  %r0.1 = fadd  <2 x float> %v0.1, %a1
  store <2 x float> %r0.1, ptr %p0, align 8
  %v1.1 = load  <2 x float>, ptr %p1, align 8
  %r1.1 = fadd  <2 x float> %v1.1, %b1
  store <2 x float> %r1.1, ptr %p1, align 8

  ; round 2 — loads should see round 1's stores, not init
  %v0.2 = load  <2 x float>, ptr %p0, align 8
  %r0.2 = fadd  <2 x float> %v0.2, %a2
  store <2 x float> %r0.2, ptr %p0, align 8
  %v1.2 = load  <2 x float>, ptr %p1, align 8
  %r1.2 = fadd  <2 x float> %v1.2, %b2
  store <2 x float> %r1.2, ptr %p1, align 8

  %result = load <4 x float>, ptr %alloca, align 16
  ret <4 x float> %result
}

; Uneven slice sizes: 3 + 1 at offsets 0 and 3. The rewrite's tree merge
; must handle vectors of different widths (via mergeTwoVectors).
define <4 x float> @uneven_slices(<4 x float> %init, <3 x float> %a, <1 x float> %b) {
; CHECK-LABEL: define <4 x float> @uneven_slices(
; CHECK-SAME: <4 x float> [[INIT:%.*]], <3 x float> [[A:%.*]], <1 x float> [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[INIT_EXTRACT_EXTRACT:%.*]] = shufflevector <4 x float> [[INIT]], <4 x float> poison, <3 x i32> <i32 0, i32 1, i32 2>
; CHECK-NEXT:    [[INIT_EXTRACT_EXTRACT1:%.*]] = extractelement <4 x float> [[INIT]], i32 3
; CHECK-NEXT:    [[TMP0:%.*]] = bitcast float [[INIT_EXTRACT_EXTRACT1]] to <1 x float>
; CHECK-NEXT:    [[R0:%.*]] = fadd <3 x float> [[INIT_EXTRACT_EXTRACT]], [[A]]
; CHECK-NEXT:    [[R1:%.*]] = fadd <1 x float> [[TMP0]], [[B]]
; CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <1 x float> [[R1]], <1 x float> poison, <3 x i32> <i32 0, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <3 x float> [[R0]], <3 x float> [[TMP1]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    ret <4 x float> [[TMP2]]
;
entry:
  %alloca = alloca [4 x float], align 16
  store <4 x float> %init, ptr %alloca, align 16

  %p0 = getelementptr inbounds [4 x float], ptr %alloca, i32 0, i32 0
  %v0 = load <3 x float>, ptr %p0, align 4
  %r0 = fadd <3 x float> %v0, %a
  store <3 x float> %r0, ptr %p0, align 4

  %p1 = getelementptr inbounds [4 x float], ptr %alloca, i32 0, i32 3
  %v1 = load <1 x float>, ptr %p1, align 4
  %r1 = fadd <1 x float> %v1, %b
  store <1 x float> %r1, ptr %p1, align 4

  %result = load <4 x float>, ptr %alloca, align 16
  ret <4 x float> %result
}

; Direct load-to-store (slice swap): every partial store's value operand
; is exactly a previously-loaded slice, with no arithmetic in between. The
; rewriter must read each store's operand *after* load rewrites have been
; applied — otherwise the store records the (now-dead) original load and
; the final tree merge ends up consuming a poison value.
define <4 x float> @slice_swap(<4 x float> %init) {
; CHECK-LABEL: define <4 x float> @slice_swap(
; CHECK-SAME: <4 x float> [[INIT:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[INIT_EXTRACT_EXTRACT:%.*]] = shufflevector <4 x float> [[INIT]], <4 x float> poison, <2 x i32> <i32 0, i32 1>
; CHECK-NEXT:    [[INIT_EXTRACT_EXTRACT1:%.*]] = shufflevector <4 x float> [[INIT]], <4 x float> poison, <2 x i32> <i32 2, i32 3>
; CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <2 x float> [[INIT_EXTRACT_EXTRACT1]], <2 x float> [[INIT_EXTRACT_EXTRACT]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    ret <4 x float> [[TMP0]]
;
entry:
  %alloca = alloca [4 x float], align 16
  store <4 x float> %init, ptr %alloca, align 16

  %p0 = getelementptr inbounds [4 x float], ptr %alloca, i32 0, i32 0
  %p1 = getelementptr inbounds [4 x float], ptr %alloca, i32 0, i32 2

  %v0 = load <2 x float>, ptr %p0, align 8
  %v1 = load <2 x float>, ptr %p1, align 8

  ; slice0 <- slice1's loaded value; slice1 <- slice0's loaded value.
  store <2 x float> %v1, ptr %p0, align 8
  store <2 x float> %v0, ptr %p1, align 8

  %result = load <4 x float>, ptr %alloca, align 16
  ret <4 x float> %result
}

; Load-only single-element slice. The init seed for a 1-element range is
; produced by extractelement (a scalar), and a slice with no partial store
; never updates that entry.
define <4 x float> @load_only_single_element_slice(<4 x float> %init, <2 x float> %a, <1 x float> %b) {
; CHECK-LABEL: define <4 x float> @load_only_single_element_slice(
; CHECK-SAME: <4 x float> [[INIT:%.*]], <2 x float> [[A:%.*]], <1 x float> [[B:%.*]]) {
; CHECK-NEXT:  [[ENTRY:.*:]]
; CHECK-NEXT:    [[INIT_EXTRACT_EXTRACT:%.*]] = shufflevector <4 x float> [[INIT]], <4 x float> poison, <2 x i32> <i32 0, i32 1>
; CHECK-NEXT:    [[INIT_EXTRACT_EXTRACT1:%.*]] = extractelement <4 x float> [[INIT]], i32 2
; CHECK-NEXT:    [[INIT_EXTRACT_VEC:%.*]] = bitcast float [[INIT_EXTRACT_EXTRACT1]] to <1 x float>
; CHECK-NEXT:    [[INIT_EXTRACT_EXTRACT2:%.*]] = extractelement <4 x float> [[INIT]], i32 3
; CHECK-NEXT:    [[INIT_EXTRACT_VEC3:%.*]] = bitcast float [[INIT_EXTRACT_EXTRACT2]] to <1 x float>
; CHECK-NEXT:    [[R0:%.*]] = fadd <2 x float> [[INIT_EXTRACT_EXTRACT]], [[A]]
; CHECK-NEXT:    [[R1:%.*]] = fadd <1 x float> [[INIT_EXTRACT_VEC]], [[B]]
; CHECK-NEXT:    [[TMP0:%.*]] = shufflevector <1 x float> [[R1]], <1 x float> poison, <2 x i32> <i32 0, i32 poison>
; CHECK-NEXT:    [[TMP1:%.*]] = shufflevector <2 x float> [[R0]], <2 x float> [[TMP0]], <3 x i32> <i32 0, i32 1, i32 2>
; CHECK-NEXT:    [[TMP2:%.*]] = shufflevector <1 x float> [[INIT_EXTRACT_VEC3]], <1 x float> poison, <3 x i32> <i32 0, i32 poison, i32 poison>
; CHECK-NEXT:    [[TMP3:%.*]] = shufflevector <3 x float> [[TMP1]], <3 x float> [[TMP2]], <4 x i32> <i32 0, i32 1, i32 2, i32 3>
; CHECK-NEXT:    [[V2_FROM_INIT:%.*]] = bitcast <1 x float> [[INIT_EXTRACT_VEC3]] to float
; CHECK-NEXT:    [[FINAL:%.*]] = insertelement <4 x float> [[TMP3]], float [[V2_FROM_INIT]], i32 0
; CHECK-NEXT:    ret <4 x float> [[FINAL]]
;
entry:
  %alloca = alloca [4 x float], align 16
  store <4 x float> %init, ptr %alloca, align 16

  ; slice 0: load+store at (0,2)
  %p0 = getelementptr inbounds [4 x float], ptr %alloca, i32 0, i32 0
  %v0 = load <2 x float>, ptr %p0, align 8
  %r0 = fadd <2 x float> %v0, %a
  store <2 x float> %r0, ptr %p0, align 8

  ; slice 1: load+store at (2,3) — single-element with a store
  %p1 = getelementptr inbounds [4 x float], ptr %alloca, i32 0, i32 2
  %v1 = load <1 x float>, ptr %p1, align 4
  %r1 = fadd <1 x float> %v1, %b
  store <1 x float> %r1, ptr %p1, align 4

  ; slice 2: load-only at (3,4) — single-element, no store (the crash case)
  %p2 = getelementptr inbounds [4 x float], ptr %alloca, i32 0, i32 3
  %v2 = load <1 x float>, ptr %p2, align 4

  %result = load <4 x float>, ptr %alloca, align 16

  ; consume %v2 so the load isn't trivially dead before SROA runs
  %v2_from_init = bitcast <1 x float> %v2 to float
  %final = insertelement <4 x float> %result, float %v2_from_init, i32 0
  ret <4 x float> %final
}
